name: Build Android
on: [push, pull_request]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: BrightID
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
#      - name: build
#        run: |
#          sh ./scripts/build_debug.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: eslint
          path: ./node_modules/.bin/
#          name: app-debug.apk
#          path: android/app/build/outputs/apk/debug/
